config/routes.rb
Rails.application.routes.draw do
  resources :channels
  resources :discussions do
    resources :replies
    
  end
  devise_for :users, controllers: { registrations: "registrations" }
  get "home" =>'home#index'
  root "discussions#index"

end

app/views/shared/_discussions.html.erb
<div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Latest Discussions</h3>
  <div class="discussions">
    <% @discussions.each do |discussion| %>
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
          <%= gravatar_image_tag(discussion.user.email, class:'border-radius-50', size: 48, alt: discussion.user.username) %>
        </div>
        <div class="column is-8">
          <%= link_to discussion do %>
            <h3 class="title is-5"><%= discussion.title %></h3>
          <% end %>
          <div class="content">
            <%= truncate(strip_markdown(discussion.content), length: 140) %>
            <p><em><small>Posted <%= time_ago_in_words(discussion.created_at) %> ago in
              <% if discussion.channel %>
                <%= link_to discussion.channel.channel, discussion.channel %>
              <% end %>
              by <%= discussion.user.username %>
              </small>
              </em>
            </p>
          </div>
        </div>

        <% if discussion_author(discussion) || has_role?(:admin) %>
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_discussion_path(discussion), class:'button' %>
          <%= link_to 'Delete', discussion, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
        </div>
        <% end %>

      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Discussions</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <% if user_signed_in? %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
              <%= link_to current_user.username, edit_user_registration_path, class:"navbar-item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
         <% else %>
         <div class="navbar-item">
          <div class="field is-grouped">

            <p class="control">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </p>

            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class: "button is-light"%>
            </p>

            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class: "button is-light" %>
            </p>
          </div>
          </div>
          <% end %>

        </div>
    </div>
  </nav>